# Generated by Django 4.1.3 on 2022-12-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image_name',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
